const data = [
    {
        itemName: "How is the Internet work generally?",
        itemCategory: "Accessing a website via the Internet",
        itemLink: "https://www.geeksforgeeks.org/how-does-the-internet-work/",
        itemCopy: "Firstly, you’ll be required to connect your system or PC with any router or modem to establish a connection. This connection is the base of the internet connection. When you open the browser and start typing something like “www.google.com”, your system will push a query command to your ISP (Internet Service Provider) that is connected with other servers that store and process data. Now, the web browser will start indexing the URL that you’ve entered and will fetch the details in numeric format (in their language to identify the address (unique) that you’re trying to reach. Next, now your browser will start sending the HTTP request where you’re trying to reach and send a copy of the website on the user’s system. Note: The server will send data in the form of small packets (from the website to the browser) Once all the data (of small packets) is received at the user’s end (PC/Laptop), the browser will start arranging all those small packets and later will form a collective file (here, the browser will gather all the small packets and rearrange them just like a puzzle) and then you’ll be able to see the contents of that website",
        itemImg: "pic/HowDoesitWorkWhenYouGoogleFromaWebBrowser.png"
    },
    {
        itemName: "What are HTTP and HTTPS? How do they work?",
        itemCategory: "HTTP/HTTPS",
        itemLink: "https://www.geeksforgeeks.org/difference-between-http-and-https-2/",
        itemCopy: "HTTP: HTTP is a client-server protocol where a client, often a web browser or an application, sends requests to a server. The client may also be a robot that crawls the web to maintain a search engine index. Each request is handled by the server, which responds accordingly. Throughout this process, various entities, known as proxies, act as gateways or caches, facilitating different operations between the client and server. HTTP (Hypertext Transfer Protocol) is the protocol used for transferring data over the web. When you enter a URL in your browser, it sends a request to the web server, usually using a method like GET (to retrieve data). The server processes this request and responds with a status code (like 200 for success) and the requested content (such as HTML). Your browser then renders the received data, displaying the webpage for you to view. In essence, HTTP facilitates the communication between clients (browsers) and servers to fetch and display web content. HTTPS: Hypertext Transfer Protocol Secure is a protocol that is used to communicate between the user browser and the website. It also helps in the transfer of data. It is the secure variant of HTTP. To make the data transfer more secure, it is encrypted. Encryption is required to ensure security while transmitting sensitive information like passwords, contact information, etc. HTTPS is a secure version of HTTP that uses Secure Socket Layer (SSL) and Transport Layer Security (TLS) protocols to protect communication between browsers and web servers. It adds a layer of SSL/TLS on top of the standard HTTP protocol, allowing for the same workflow while ensuring that data exchanged is encrypted and decrypted for safety. This secure connection safeguards the integrity and confidentiality of the information being transmitted.",
        itemImg: "pic/HTTPSdrawio-660x368.png"
    },
    {
        itemName: "What is Domain Name? | How does Domain Name work?",
        itemCategory: "Domain Name",
        itemLink: "https://doteasy.com/blog/how-do-domains-work",
        itemCopy: "The simplest explanation of a domain name is that it is the address that the browser uses to find a website. In other words, it is a unique identifier for a website or email account. Expanding on this explanation, a domain name is a human-friendly label of a specific IP address. Every domain name consists of at least two parts: the actual domain name and the domain extension. For example, Doteasy.com. In this example, the actual domain name is “Doteasy” and “.com” is the domain extension. In order for your website to be viewable on the Internet, it needs to be connected to the Internet (ie. your web files need to be on a computer that is connected to the Internet) and thus, it will have an IP address. Trying to remember the IP address for every website on the Internet is a difficult task, and that’s where domain names come in. A domain name tells other machines (computers, mobile devices, etc.) which web server they need to look to for your web files.",
        itemImg: "pic/what-is-a-domain-name-1.jpg"
    },
    {
        itemName: "What is Hosting? | How does Hosting work?",
        itemCategory: "Hosting Web",
        itemLink: "https://www.namecheap.com/hosting/what-is-web-hosting-definition/",
        itemCopy: "In a nutshell, web hosting is the process of renting or buying space to house a website on the World Wide Web. Website content such as HTML, CSS, and images has to be housed on a server to be viewable online. Web hosting involves uploading website files from a local computer to a web server, which allocates its resources (RAM, hard drive space, bandwidth) to the hosted sites. Choosing the right hosting plan is like selecting office space: you need to consider your needs and growth potential. - Shared Hosting is akin to renting a workstation in a busy co-working space, where resources are shared with others. It's ideal for small websites but unsuitable for large-scale projects. - Virtual Private Server (VPS) is like having an office in a business park, providing more privacy and customization options, making it suitable for medium-sized businesses. - Dedicated Server Hosting is comparable to renting an entire office building, offering maximum control and resources, best for websites that require high performance and reliability. However, it can be costly if the space isn't fully utilized.",
        itemImg: "pic/graphic-2.2-1.png"
    },
    {
        itemName: "What is DNS? | How does DNS work?",
        itemCategory: "Domain Name",
        itemLink: "https://www.cloudflare.com/learning/dns/what-is-dns/",
        itemCopy: `The Domain Name System (DNS) is the phonebook of the Internet. Humans access information online through domain names, like nytimes.com or espn.com. Web browsers interact through Internet Protocol (IP) addresses. DNS translates domain names to IP addresses so browsers can load Internet resources. Each device connected to the Internet has a unique IP address which other machines use to find the device. DNS servers eliminate the need for humans to memorize IP addresses such as 192.168.1.1 (in IPv4), or more complex newer alphanumeric IP addresses such as 2400:cb00:2048:1::c629:d7a2 (in IPv6). The process of DNS resolution involves converting a hostname (such as www.example.com) into a computer-friendly IP address (such as 192.168.1.1). An IP address is given to each device on the Internet, and that address is necessary to find the appropriate Internet device - like a street address is used to find a particular home. When a user wants to load a webpage, a translation must occur between what a user types into their web browser (example.com) and the machine-friendly address necessary to locate the example.com webpage. In order to understand the process behind the DNS resolution, it’s important to learn about the different hardware components a DNS query must pass between. For the web browser, the DNS lookup occurs "behind the scenes" and requires no interaction from the user’s computer apart from the initial request.`,
        itemImg: "pic/what_is_dns.png"
    },
    {
        itemName: "What is Browser? | How does Browser work?",
        itemCategory: "Browser",
        itemLink: "https://www.browserstack.com/guide/what-is-browser",
        itemCopy: `A web browser is software that allows users to access and view content on the World Wide Web. Its main function is to retrieve web pages, images, videos, and other files from servers and display them on your device. When you enter a website's URL and hit Enter, the browser sends a request to the server using protocols like HTTP or HTTPS. The server then responds by sending the website's files, typically written in HTML, CSS, and JavaScript. The browser interprets this code and renders it into a user-friendly web page. Essentially, the browser serves as a bridge between users and websites, enabling easy navigation of internet content. Browsers are responsible for retrieving and displaying web content to users. When a user enters a URL or clicks on a link, the browser initiates a complex series of actions to retrieve the web content from a server and display it on the user’s device. The process of accessing a web page starts with Domain Name System (DNS) resolution, where the browser translates the domain name into an IP address to find the server hosting the page. The browser then sends an HTTP request to the server, specifying the resource path and parameters. Upon receiving the request, the server responds with the requested resource in the form of HTML, CSS, and JavaScript code. The browser’s rendering engine interprets this code, applying CSS styles for formatting and layout, and executing JavaScript for interactivity. As new content loads or changes occur, the browser updates the display to reflect these modifications on the user's device.`,
        itemImg: "pic/Screenshot_2024-10-19_215048-transformed.png"
    }
];

export { data };